import { useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { ArrowDownRight, ArrowRight, BookOpen, ShieldCheck, Users, Sparkles } from 'lucide-react';
import { endpoints } from '../services/api';
import { Logo } from '../components/Logo';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';

function getSafeReturnUrl(value) {
  if (!value || !value.startsWith('/') || value.startsWith('//')) return '/dashboard';
  try { const destination = new URL(value, window.location.origin); return destination.origin === window.location.origin ? `${destination.pathname}${destination.search}${destination.hash}` : '/dashboard'; }
  catch { return '/dashboard'; }
}

export function AuthPage({ register = false }) { const { user, signIn } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const toast = useToast(); const [busy, setBusy] = useState(false); const [role, setRole] = useState('learner'); const [error, setError] = useState(''); const [formElement, setFormElement] = useState(null);
  function fillDemo(email) { if (!formElement) return; formElement.elements.email.value = email; formElement.elements.password.value = 'Password123!'; setError(''); toast('Opening the demo account…'); formElement.requestSubmit(); }
  const returnUrl = new URLSearchParams(location.search).get('returnUrl');
  if (user) return <Navigate to={register ? '/dashboard' : getSafeReturnUrl(returnUrl)} replace/>;
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); const form = new FormData(e.currentTarget); const body = Object.fromEntries(form.entries()); if (register) body.role = role; try { const result = register ? await endpoints.register(body) : await endpoints.login(body); if (!result.token) throw new Error('Account created. Please log in to continue.'); signIn(result); toast(register ? 'Welcome to OpenBook — you’re all set.' : `Welcome back, ${result.user.name.split(' ')[0]}.`); navigate(register ? '/dashboard' : getSafeReturnUrl(returnUrl)); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="auth-page"><div className="auth-aside"><Link to="/" aria-label="OpenBook home"><Logo/></Link><div className="auth-aside-copy"><div className="eyebrow"><span className="eyebrow-line"/>OPENBOOK</div><h2>Courses,<br/>lessons, and<br/><span>progress.</span></h2></div><span className="auth-aside-foot">COURSE PROGRESS TRACKER</span></div><div className="auth-form-side"><Link className="back-link" to="/"><ArrowDownRight size={16}/> Back to home</Link><form className="auth-form" ref={setFormElement} onSubmit={submit}><div className="eyebrow"><span className="eyebrow-line"/>{register ? 'CREATE YOUR ACCOUNT' : 'GOOD TO HAVE YOU BACK'}</div><h1>{register ? 'Create your account.' : 'Welcome back.'}</h1><p className="auth-subtitle">{register ? 'Create a learner or instructor account.' : 'Sign in to access your courses.'}</p>{!register && <div className="demo-access"><div><Sparkles size={15}/><span><strong>Quick demo access</strong><small>Explore both roles</small></span></div><button type="button" onClick={() => fillDemo('learner1@test.com')}><BookOpen size={14}/> Demo learner</button><button type="button" onClick={() => fillDemo('inst1@test.com')}><Users size={14}/> Demo instructor</button></div>}{register && <><label>Your name<input name="name" placeholder="Alex Morgan" required autoComplete="name"/></label></>}
    <label>Email address<input name="email" type="email" placeholder="you@example.com" required autoComplete="email"/></label><label>Password<input name="password" type="password" placeholder="At least 6 characters" required minLength="6" autoComplete={register ? 'new-password' : 'current-password'}/></label>{register && <div className="role-select"><span>I’m here to</span><div><button type="button" className={role === 'learner' ? 'selected' : ''} onClick={() => setRole('learner')}><BookOpen size={16}/> Learn</button><button type="button" className={role === 'instructor' ? 'selected' : ''} onClick={() => setRole('instructor')}><Users size={16}/> Teach</button></div></div>}{error && <div className="form-error" role="alert">{error}</div>}<button className="button button-primary button-wide" disabled={busy}>{busy ? 'One moment…' : register ? 'Create my account' : 'Log in'} <ArrowRight size={17}/></button><div className="auth-switch">{register ? 'Already have an account?' : 'New around here?'} <Link to={register ? '/login' : '/register'}>{register ? 'Log in' : 'Create an account'}</Link></div><div className="auth-secure"><ShieldCheck size={15}/> Your learning space is private and secure</div></form></div></div>;
}
